#!/usr/bin/php
<?php
/**
 * @file
 * @version 0.1
 * @copyright 2019 CN-Consult GmbH
 * @author Jens Stahl <jens.stahl@cn-consult.eu>
 *
 * License: Please check the LICENSE file for more information.
 */

require_once ("vendor/autoload.php");
use Symfony\Component\Console\Application;

/**
 * Custom auto loader for own files.
 * @param string $_className The name of the class that gets sourced.
 */
function customAutoLoader($_className)
{
    $strippedClassName = strtolower(substr($_className, strrpos($_className, '\\') + 1));
    foreach (array(".", "commands", "profitbricksapi") as $directory)
    {
        $filepath = __DIR__."/".$directory."/".$strippedClassName.'.php';
        if (file_exists($filepath))
        {
            require_once $filepath;
            break;
        }
    }
}
spl_autoload_register("customAutoLoader");

$application = new Application();
foreach(array("SnapshotListCommand", "SnapshotCreateFromAttachedDisksCommand", "SnapshotDeleteCommand", "SnapshotAutoCreateCommand",
            "SnapshotAutoDeleteCommand", "SnapshotCheckerCommand", "ServerListCommand", "DiskListCommand", "ServerStartCommand", "ServerStopCommand") as $command)
{
    $command = "\\PBST\\Commands\\".$command;
    $application->add(new $command());
}
$application->run();